import sys
import os
import requests
import sqlite3
import json
import re

# Set stdout to UTF-8 to avoid Windows console CP1252 emoji encoding crashes
if hasattr(sys.stdout, 'reconfigure'):
    sys.stdout.reconfigure(encoding='utf-8')

# Insert project parent to sys.path
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, PROJECT_ROOT)

BASE_URL = "http://127.0.0.1:5000"

def get_authenticated_session():
    session = requests.Session()
    
    # 1. GET /login to retrieve csrf token
    print("🔑 Fetching login page to extract CSRF token...")
    r = session.get(f"{BASE_URL}/login")
    if r.status_code != 200:
        print(f"❌ Failed to fetch login page. Status: {r.status_code}")
        sys.exit(1)
        
    # Extract csrf_token using regex
    match = re.search(r'name="csrf_token"\s+value="([^"]+)"', r.text)
    if not match:
        print("❌ Could not find csrf_token on the login page!")
        sys.exit(1)
    csrf_token = match.group(1)
    print(f"✅ Extracted CSRF token successfully.")
    
    # 2. POST /login with email, password, and csrf_token
    print("🔑 Authenticating as admin...")
    payload = {
        "email": "admin@marketing.ai",
        "password": "admin123",
        "csrf_token": csrf_token
    }
    r_login = session.post(f"{BASE_URL}/login", data=payload, allow_redirects=True)
    if r_login.status_code != 200 or "login" in r_login.url:
        print("❌ Login failed! Please verify credentials or server status.")
        sys.exit(1)
        
    print("✅ Successfully authenticated as admin using session!")
    
    # Attach X-CSRFToken header to all session requests
    session.headers.update({"X-CSRFToken": csrf_token})
    return session

def run_e2e_test():
    print("=" * 60)
    print("🚀 AUTOMATED E2E USER TEST SUITE (SRE SECURE)")
    print("=" * 60)

    # Establish authenticated session
    session = get_authenticated_session()

    # -------------------------------------------------------------
    # Step 1: Start a live_links workflow
    # -------------------------------------------------------------
    print("\n[Step 1] Triggering 'live_links' workflow...")
    payload = {"sector": "live_links"}
    try:
        r = session.post(f"{BASE_URL}/api/run_pipeline", json=payload, timeout=90)
    except Exception as e:
        print(f"❌ Failed to connect to server: {e}")
        print("Please ensure the Flask server is running on http://127.0.0.1:5000")
        sys.exit(1)

    if r.status_code != 200:
        print(f"❌ Pipeline failed with status code {r.status_code}: {r.text}")
        sys.exit(1)

    res = r.json()
    if res.get("status") != "success":
        print(f"❌ Pipeline returned error status: {res.get('message')}")
        sys.exit(1)

    products = res.get("data", [])
    if not products:
        print("❌ No products generated by the pipeline.")
        sys.exit(1)

    print(f"✅ Pipeline ran successfully in {res.get('pipeline_time')}s!")
    print(f"✅ Loaded {len(products)} products in sector '{res.get('sector_display')}'.")

    # Pick the first product for redirection test
    test_prod = products[0]
    prod_id = test_prod.get("id")
    title = test_prod.get("title")
    sector = test_prod.get("sector", "live_links")
    aff_link = test_prod.get("affiliate_link", "https://amazon.in/dp/test")
    price = test_prod.get("price")
    rev = test_prod.get("revenue", {})
    score = rev.get("revenue_score", 0)
    commission = rev.get("est_commission_pct", 0)

    print(f"👉 Selected product for test click:")
    print(f"   ID: {prod_id}")
    print(f"   Title: {title}")
    print(f"   Original Affiliate Link: {aff_link}")

    # -------------------------------------------------------------
    # Step 2: Click through a /go/<product_id> link
    # -------------------------------------------------------------
    print("\n[Step 2] Simulating click through /go/<product_id> tracking link...")
    click_url = f"{BASE_URL}/go/{prod_id}"
    params = {
        "url": aff_link,
        "title": title,
        "sector": sector,
        "score": score,
        "commission": commission
    }
    
    r_click = session.get(click_url, params=params, allow_redirects=False, timeout=10)
    if r_click.status_code not in (302, 200):
        print(f"❌ Click redirect failed with status code {r_click.status_code}: {r_click.text}")
        sys.exit(1)

    print(f"✅ Click registered successfully! Status: {r_click.status_code}")
    if r_click.status_code == 302:
        print(f"✅ Correctly redirected to safe affiliate URL: {r_click.headers.get('Location')}")

    # -------------------------------------------------------------
    # Step 3: Check History page
    # -------------------------------------------------------------
    print("\n[Step 3] Fetching history logs and verifying dynamic statistics & click syncing...")
    r_hist = session.get(f"{BASE_URL}/api/history", params={"sector": "live_links"}, timeout=10)
    if r_hist.status_code != 200:
        print(f"❌ Failed to fetch history: {r_hist.text}")
        sys.exit(1)

    hist_data = r_hist.json()
    if hist_data.get("status") != "success":
        print(f"❌ History API returned error: {hist_data.get('message')}")
        sys.exit(1)

    stats = hist_data.get("stats", {})
    campaigns = hist_data.get("campaigns", [])
    
    print("✅ Successfully fetched history!")
    print(f"📊 Stats for live_links:")
    print(f"   Total Campaigns: {stats.get('total')}")
    print(f"   Total Views: {stats.get('views')}")
    print(f"   Total Clicks tracked: {stats.get('clicks')}")

    # Verify that the click we simulated is counted!
    if stats.get('clicks', 0) < 1:
        print("❌ Clicks are not registering correctly in the affiliate tracker database.")
        sys.exit(1)
    
    print("✅ Verified: dynamic stats reflect live affiliate click counts!")

    # Find our campaign row and check dynamic clicks sync
    matched_camp = None
    for c in campaigns:
        if c.get("product_id") == prod_id:
            matched_camp = c
            break

    if not matched_camp:
        print(f"⚠️ Warning: Could not find campaign row with product_id {prod_id} in history response.")
    else:
        print(f"✅ Campaign Row Dynamic Clicks: {matched_camp.get('total_clicks')}")
        if matched_camp.get('total_clicks', 0) < 1:
            print("❌ Campaign Row click sync is failing!")
            sys.exit(1)
        print("✅ Verified: Individual campaign row clicks are dynamically synced!")

    # -------------------------------------------------------------
    # Step 4: Run a manual retargeting sweep
    # -------------------------------------------------------------
    print("\n[Step 4] Triggering manual Retargeting Sweep...")
    r_retarget = session.post(f"{BASE_URL}/api/run_retargeting", timeout=30)
    if r_retarget.status_code != 200:
        print(f"❌ Retargeting engine sweep failed: {r_retarget.text}")
        sys.exit(1)

    retarget_res = r_retarget.json()
    if retarget_res.get("status") != "success":
        print(f"❌ Retargeting failed: {retarget_res.get('message')}")
        sys.exit(1)

    plans = retarget_res.get("plans", [])
    print(f"✅ Generated {len(plans)} retargeting plans immediately!")
    for p in plans:
        print(f"   - Product: {p.get('product_title')} | Strategy: {p.get('strategy')}")

    # Verify retargeting stats are logged
    r_retarget_stats = session.get(f"{BASE_URL}/api/retargeting_stats", timeout=10)
    retarget_stats = r_retarget_stats.json()
    recent_logs = retarget_stats.get("recent_logs", [])
    print(f"✅ Retargeting Activity Log has {len(recent_logs)} recent actions logged.")
    if len(recent_logs) < 1:
        print("❌ Retargeting logs are empty or were not recorded to the database.")
        sys.exit(1)
    print("✅ Verified: Retargeting activity logs successfully populated in database!")

    # -------------------------------------------------------------
    # Step 5: Confirm the UI looks consistent
    # -------------------------------------------------------------
    print("\n[Step 5] Performing visual layout integrity checklist...")
    
    # Check index and history HTML templates existence and load status
    r_index = session.get(BASE_URL, timeout=10)
    r_hist_page = session.get(f"{BASE_URL}/history", timeout=10)
    
    if r_index.status_code == 200 and r_hist_page.status_code == 200:
        print("✅ Dashboard page (/) is healthy and rendering.")
        print("✅ History page (/history) is healthy and rendering.")
    else:
        print(f"❌ UI templates failed to render (Dashboard: {r_index.status_code}, History: {r_hist_page.status_code})")
        sys.exit(1)

    # Check that fallback graphic serves cleanly
    r_graphic = session.get(f"{BASE_URL}/image/test_fallback_graphic.jpg", timeout=10)
    if r_graphic.status_code == 200:
        print("✅ Fallback graphic asset serves perfectly!")
    else:
        print(f"❌ Fallback graphic is missing or server cannot serve it. Status: {r_graphic.status_code}")
        sys.exit(1)

    # Check scheduler status endpoint
    r_sched = session.get(f"{BASE_URL}/api/scheduler_status", timeout=10)
    sched_status = r_sched.json()
    if sched_status.get("status") == "success":
        print(f"✅ Scheduler status verified: active={sched_status.get('scheduler_running')} jobs={len(sched_status.get('jobs', []))}")
    else:
        print("❌ Scheduler status is broken.")
        sys.exit(1)

    print("\n" + "=" * 60)
    print("🏆 ALL 5 STEPS OF THE USER TEST SUITE COMPLETED WITH 100% SUCCESS!")
    print("=" * 60)

if __name__ == '__main__':
    run_e2e_test()
